[package]
name = "KYC"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
# Arkworks for Groth16 (as recommended in the mobile guide)
ark-groth16 = "0.4"
ark-bn254 = "0.4"  # BN254 curve - optimal for mobile as per guide
ark-ff = "0.4"
ark-relations = "0.4"
ark-serialize = "0.4"
ark-std = { version = "0.4", default-features = false }
ark-snark = "0.4"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"
base64 = "0.21"

# WASM
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1"

# Hashing
sha2 = "0.10"

[dev-dependencies]
wasm-bindgen-test = "0.3"

# Mobile-optimized build profile (from the guide)
[profile.release]
opt-level = "z"          # Optimize for smallest size
lto = true               # Link Time Optimization
codegen-units = 1        # Better optimization
panic = "abort"          # Smaller binary
strip = true             # Strip symbols

# Even more aggressive mobile optimization
[profile.mobile]
inherits = "release"
opt-level = "z"
lto = "fat"
panic = "abort"
strip = true

# No stdsimd issues with arkworks!